build:
  id: 1010202
  version: 1.2.3
  name: "Default-GIT-Production-Build"
  type: " GIT Default Build"

  #creating this configuration file for config demo and now we need to map it with config server
